name: animecx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  ffi: ^2.1.3
  dio: ^5.8.0+1
  http: ^1.2.0
  #video_player_win: ^3.1.1
  shared_preferences: ^2.5.3
  window_manager: ^0.4.3
  image: ^4.5.4
  desktop_screenshot: ^0.0.4
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_windows_video: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/js/
    - assets/sounds/
    - assets/images/
    - assets/images/hunter_x_hunter/intro/1.png
    - assets/images/hunter_x_hunter/intro/2.png
    - assets/images/hunter_x_hunter/outro/1.png
